/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import dao.DEmpleado;
import javax.swing.JOptionPane;
import modelos.Cargo;

/**
 *
 * @author megan
 */
public class frmEmpleado extends javax.swing.JFrame {
    DEmpleado DE = new DEmpleado();
    private int pos = 0;
    /**
     * Creates new form frmEmpleado
     */
    public frmEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblEmpe = new javax.swing.JLabel();
        jTxtEmpe = new javax.swing.JTextField();
        jLblCargo = new javax.swing.JLabel();
        jCmbCargo = new javax.swing.JComboBox<>();
        jLblSalario = new javax.swing.JLabel();
        jTxtSalario = new javax.swing.JTextField();
        jBtnAgregar = new javax.swing.JButton();
        jBtnAumentar10 = new javax.swing.JButton();
        jBtnAumentar7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblEmpe.setText("Empleado:");

        jLblCargo.setText("Cargo");

        jCmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analista", "Programador", "Supervisor" }));
        jCmbCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbCargoActionPerformed(evt);
            }
        });

        jLblSalario.setText("Salario");

        jBtnAgregar.setText("Agregar");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jBtnAumentar10.setText("Aumentar los salarios de los Programadores en un 10 %");
        jBtnAumentar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAumentar10ActionPerformed(evt);
            }
        });

        jBtnAumentar7.setText("Aumentar en un 7% el salario de los empleados que no sean Programador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnAumentar10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblEmpe)
                            .addComponent(jLblCargo)
                            .addComponent(jLblSalario))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtEmpe, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnAumentar7, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEmpe)
                    .addComponent(jTxtEmpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCargo)
                    .addComponent(jCmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblSalario)
                    .addComponent(jTxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jBtnAgregar)
                .addGap(18, 18, 18)
                .addComponent(jBtnAumentar10)
                .addGap(18, 18, 18)
                .addComponent(jBtnAumentar7)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbCargoActionPerformed

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        // TODO add your handling code here:
        String nombre = jTxtEmpe.getText();
        Cargo c;
        double precio = Double.parseDouble(jTxtSalario.getText());
        
        if (jCmbCargo.getSelectedIndex()==0)
        {
            c = Cargo.ANALISTA;
        }
        
         if (jCmbCargo.getSelectedIndex()==1)
        {
            c = Cargo.PROGRAMADOR;
        }else{
             c = Cargo.SUPERVISOR;
         }
         
         int b = DE.agregarEmpleado(nombre, c, precio);
         
         if (b==1){
             JOptionPane.showMessageDialog(this, "Registro Agregado...", "Agregar", JOptionPane.INFORMATION_MESSAGE);
             limpiar();
         }
         
         if (b==0){
             JOptionPane.showMessageDialog(this, "Error al Agregar...", "Agregar", JOptionPane.ERROR_MESSAGE);
             
         }
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jBtnAumentar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAumentar10ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBtnAumentar10ActionPerformed
    
    private void limpiar(){
        jTxtEmpe.setText("");
        jCmbCargo.setSelectedIndex(-1);
        jTxtSalario.setText("");
        jTxtEmpe.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnAumentar10;
    private javax.swing.JButton jBtnAumentar7;
    private javax.swing.JComboBox<String> jCmbCargo;
    private javax.swing.JLabel jLblCargo;
    private javax.swing.JLabel jLblEmpe;
    private javax.swing.JLabel jLblSalario;
    private javax.swing.JTextField jTxtEmpe;
    private javax.swing.JTextField jTxtSalario;
    // End of variables declaration//GEN-END:variables
}
